### PR TITLE
New Game added

### LINKED ISSUE #1097: [New game]: Pixel Painter Game
### 🎮 Game Request

Game logic and basic description:Pixel Painter is an interactive web-based drawing application that allows users to create pixel art. It features a canvas for drawing, a color picker, an undo functionality, and a clear button. The interface includes smooth animations and an intuitive user experience.

### Drawing

1. **Select a Color**: Use the color picker in the toolbar to choose your desired drawing color.
2. **Start Drawing**: Click and hold the left mouse button on the canvas to start drawing. Move the mouse to draw.
3. **Stop Drawing**: Release the left mouse button to stop drawing.

### Clear the Canvas

- **Clear Button**: Click the "Clear" button in the toolbar to erase the entire canvas and start fresh.

### Undo

- **Undo Button**: Click the "Undo" button to revert to the previous state. The application maintains a stack of up to 10 previous states.

## Features

- **Color Picker**: Allows you to select any color for drawing.
- **Clear Canvas**: Clears all drawings on the canvas, providing a blank slate.
- **Undo Functionality**: Reverts the canvas to the previous state, allowing for correction of mistakes.
- **Grid Overlay**: A grid is displayed over the canvas to help with pixel alignment and precision.
- **Smooth Animations**: Buttons and color picker have smooth transition animations for an enhanced user experience.
- 
## Usage

- **Drawing**: Select a color and start drawing on the canvas.
- **Clearing**: Click the "Clear" button to reset the canvas.
- **Undoing**: Click the "Undo" button to revert to the previous state.

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/GameSphere-MultiPlayer/GameSphere/blob/main/.github/Contributor.md) of this project.

### PR DESCRIPTION
**Pull request by Nayanika1402**
Closes #1097

## Description

Pixel Painter is an interactive web-based drawing application that allows users to create pixel art. It features a canvas for drawing, a color picker, an undo functionality, and a clear button. The interface includes smooth animations and an intuitive user experience.

## Screenshot Section

Screenshot 2024-07-28 094158

## Checklist 

- [x] I have added image into screensort in "SinglePlayer - Games/Banner - image" in this section*
- [x] I have added game into "additionalpage/game.html"*
- [x] I have added Update main README.md file*

## Task

- [ ] Follow Us On social media -
- [ ]      <a href="https://github.com/GameSphere-MultiPlayer" target="_blank">GitHub</a>
- [ ]      <a href="https://www.linkedin.com/company/gamesphere-multiplayer/" target="_blank">LinkedIn</a>
- [ ]     <a href="https://www.youtube.com/@durgesh4993/channels" target="_blank">YouTube</a>
- [ ]      <a href="https://discord.com/invite/dakzwdz4ev" target="_blank">Discord</a>

## Enter you User Id's:
LinkedIn:
<br>GitHub: 
<br>YouTube:
<br>Discord:

If you Follow us in both social medias we provide 'level2' 
*Only First time

### CODE REVIEW

**Review by Durgesh4993 — APPROVED** [review]
Ok

**Review by Durgesh4993 — COMMENTED** [review]
Resolve Conflict

**Comment by Nayanika1402** [comment]
@Durgesh4993 Conflicts resolved kindly merge my pr.

**Comment by Nayanika1402** [comment]
@Durgesh4993 conflicts resolved

**Comment by Nayanika1402** [comment]
@Durgesh4993 please approve my request.

**Comment by Nayanika1402** [comment]
@Durgesh4993 Please approve my request.

**Pull request merged**
