### PR TITLE
Earth_Guardian game added

### LINKED ISSUE #943: [Game]:  Earth Guardian
## Game Name 
 Earth Guardian

## Description

Earth Guardian is a remake of the classic Space shooter type of games, with 8-bit (pixel art) assets. This project used free assets (music and graphics) provided by [Jonathan So](https://jonathan-so.itch.io/),[KennyNL](https://kenney.nl/) and other sources, like Google images and [OpenGameArt](https://opengameart.org). This was a learning project. There will be some updates in the near future. Hope you like it, have fun!

## Screenshot Section

Earth Guardian

### Connect Us On Social Media -
- [X]  Star the repositry
- [X]  <a href="https://github.com/GameSphere-MultiPlayer" target="_blank">GitHub</a>
- [X]   <a href="https://www.linkedin.com/company/gamesphere-multiplayer/" target="_blank">LinkedIn</a>
- [X]   <a href="https://www.youtube.com/@durgesh4993/channels" target="_blank">YouTube</a>
- [X]    <a href="https://discord.com/invite/dakzwdz4ev" target="_blank">Discord</a>

### Thank you for raising issue in GameSpher 3.0

I want to add my game Earth Guardian game in your website under GSSoC'24 , so please can you assign it to me .

### PR DESCRIPTION
**Pull request by Pujan-sarkar**
Fixes #943 

## Description
Earth Guardian is a remake of the classic Space shooter type of games, with 8-bit (pixel art) assets. This project used free assets (music and graphics) provided by [Jonathan So](https://jonathan-so.itch.io/),[KennyNL](https://kenney.nl/) and other sources, like Google images and [OpenGameArt](https://opengameart.org/). This was a learning project. There will be some updates in the near future. Hope you like it, have fun!

## Screenshot Section
Earth_Guardian

## Checklist 

- [X] I have added image into screensort in "SinglePlayer - Games/Banner - image" in this section*
- [X] I have added game into "additionalpage/game.html"*
- [X] I have added Update main README.md file*

## Task

- [X] Follow Us On social media -
- [X]      <a href="https://github.com/GameSphere-MultiPlayer" target="_blank">GitHub</a>
- [X]      <a href="https://www.linkedin.com/company/gamesphere-multiplayer/" target="_blank">LinkedIn</a>
- [X]     <a href="https://www.youtube.com/@durgesh4993/channels" target="_blank">YouTube</a>
- [X]      <a href="https://discord.com/invite/dakzwdz4ev" target="_blank">Discord</a>

## Enter you User Id's:
LinkedIn:  https://www.linkedin.com/in/pujan-sarkar/
<br>GitHub:  https://github.com/Pujan-sarkar
<br>Discord: Pro_Pujan

If you Follow us in both social medias we provide 'level2' 
*Only First time

### CODE REVIEW

**Comment by Amancoder-01** [comment]
@Pujan-sarkar Resolve Conflicting files

**Comment by Pujan-sarkar** [comment]
@Amancoder-01  can you reply about this pr ?

**Comment by Pujan-sarkar** [comment]
@Amancoder-01 @Durgesh4993  please merge the pr or give a reply .....

**Review by Durgesh4993 — COMMENTED** [review]
Resolve Coflicts

**Comment by Pujan-sarkar** [comment]
@Durgesh4993  i have solved it, please check

**Comment by Pujan-sarkar** [comment]
@Durgesh4993 please give a reply or merge it please

**Comment by Pujan-sarkar** [comment]
@Durgesh4993 please merge the pr

**Comment by Pujan-sarkar** [comment]
@Durgesh4993 @Amancoder-01  there is no conflicts or something why are not you merging my pr, please do something

**Comment by Pujan-sarkar** [comment]
@Durgesh4993  pleas will you accept this , it had been 2 weeks now

**Comment by Pujan-sarkar** [comment]
@Durgesh4993  this pr is not showing in my leaderboard and not counted in my points , do you know why it is happening

**Comment by Durgesh4993** [comment]
@Pujan-sarkar Wait sometime

**Pull request merged**
