### PR TITLE
[Game]: Touch-No-Fire

### LINKED ISSUE #990: [Game]: New game
## Game Name
Touch-No-Fire-Game

## Description

Game Rules!
* Eat the food to gain score
* Do not touch the fire
* The fire multiplies once with even scores
* If you stay idle, the fire won't do anything
* Do not touch the moving fire
* Please play using arrow keys

## Screenshot Section

image

## Demo Video Section

https://github.com/GameSphere-MultiPlayer/GameSphere/assets/154777864/a88f676a-69c8-4cc9-b6e6-98e5fca1aa59

### Connect Us On Social Media -
- [X]  Star the repositry
- [X]  <a href="https://github.com/GameSphere-MultiPlayer" target="_blank">GitHub</a>
- [X]   <a href="https://www.linkedin.com/company/gamesphere-multiplayer/" target="_blank">LinkedIn</a>
- [X]   <a href="https://www.youtube.com/@durgesh4993/channels" target="_blank">YouTube</a>
- [X]    <a href="https://discord.com/invite/dakzwdz4ev" target="_blank">Discord</a>

### PR DESCRIPTION
**Pull request by Anjaliavv51**
issue #990

## Related Issue*

Closes #990 

## Description

Game Rules!
* Eat the food to gain score
* Do not touch the fire
* The fire multiplies once with even scores
* If you stay idle, the fire won't do anything
* Do not touch the moving fire
* Please play using arrow keys only!

## Screenshot Section

image

## Demo Video Section*

https://github.com/GameSphere-MultiPlayer/GameSphere/assets/154777864/28174b17-993f-4d40-a2d6-68a454d9b2ed

## Checklist 

- [X] I have added image into screensort in "SinglePlayer - Games/Banner - image" in this section*
- [X] I have added game into "additionalpage/game.html"*
- [X] I have added Update main README.md file*

## Task

- [X] Follow Us On social media -
- [X]      <a href="https://github.com/GameSphere-MultiPlayer" target="_blank">GitHub</a>
- [X]      <a href="https://www.linkedin.com/company/gamesphere-multiplayer/" target="_blank">LinkedIn</a>
- [X]     <a href="https://www.youtube.com/@durgesh4993/channels" target="_blank">YouTube</a>
- [X]      <a href="https://discord.com/invite/dakzwdz4ev" target="_blank">Discord</a>

## Enter you User Id's:
LinkedIn: [https://www.linkedin.com/in/lakshmi-pavananjali-pamidi-766760296/](url)
<br>GitHub: [https://github.com/Anjaliavv51](url)
<br>YouTube: NA
<br>Discord: anjali_23151

If you Follow us in both social medias we provide 'level2' 
*Only First time

### CODE REVIEW

**Comment by Amancoder-01** [comment]
@Anjaliavv51 Resolve Conflicting files

**Comment by Anjaliavv51** [comment]
@Amancoder-01 conflicts are resolved

**Comment by Anjaliavv51** [comment]
@Amancoder-01 please review the Game.

**Comment by Anjaliavv51** [comment]
@Amancoder-01

**Comment by Anjaliavv51** [comment]
@Durgesh4993 please review it and merge the PR

**Pull request merged**
