### PR TITLE
Solved #1050- Slay the spire game

### PR DESCRIPTION
**Pull request by Aditi22Bansal**
## Related Issue*

Closes #issue_number
#1050

## Screenshot Section
image

## Checklist 

- [x] I have added image into screensort in "SinglePlayer - Games/Banner - image" in this section*
- [x] I have added game into "additionalpage/game.html"*
- [x] I have added Update main README.md file*

## Task

- [x] Follow Us On social media -
- [x]      <a href="https://github.com/GameSphere-MultiPlayer" target="_blank">GitHub</a>
- [x]      <a href="https://www.linkedin.com/company/gamesphere-multiplayer/" target="_blank">LinkedIn</a>
- [x]     <a href="https://www.youtube.com/@durgesh4993/channels" target="_blank">YouTube</a>
- [x]      <a href="https://discord.com/invite/dakzwdz4ev" target="_blank">Discord</a>

## Enter you User Id's:
LinkedIn:
<br>GitHub: 
<br>YouTube:
<br>Discord:

If you Follow us in both social medias we provide 'level2' 
*Only First time

### CODE REVIEW

**Comment by Aditi22Bansal** [comment]
@Durgesh4993 
Kindly review and merge

**Comment by Aditi22Bansal** [comment]
@Aman1-coder 
@Durgesh4993 
Kindly review and merge

**Comment by Aditi22Bansal** [comment]
@Durgesh4993 
Kindly review and merge

**Review by Durgesh4993 — APPROVED** [review]
Approved

**Pull request merged**
