### PR TITLE
Flames Game has been created.

### LINKED ISSUE #981: [Game]: Flames Game
## Game Name
Flames Game using Javascript
## Description

The Flames game is a popular game that determines the relationship between two people based on their names. The acronym "FLAMES" stands for Friends, Lovers, Affectionate, Marriage, Enemies, and Siblings. 

## Screenshot Section
image

### Connect Us On Social Media -
- [x]  Star the repositry
- [x]  <a href="https://github.com/GameSphere-MultiPlayer" target="_blank">GitHub</a>
- [x]   <a href="https://www.linkedin.com/company/gamesphere-multiplayer/" target="_blank">LinkedIn</a>
- [x]   <a href="https://www.youtube.com/@durgesh4993/channels" target="_blank">YouTube</a>
- [x]    <a href="https://discord.com/invite/dakzwdz4ev" target="_blank">Discord</a>

### Thank you for raising issue in GameSpher 3.0
Kindly assign this issue to me under GSSOC24

### PR DESCRIPTION
**Pull request by Damini2004**
Flames Game designed using Javascript

Closes #981 

## Description

FLAMES is a fun, classic game used to predict the nature of a relationship between two people. The acronym stands for Friends, Lovers, Affectionate, Marriage, Enemies, and Siblings. By counting the letters in both names and following a specific elimination process, players discover their potential connection.

## Screenshot Section

Screenshot 2024-05-25 210820

## Checklist 

- [x] I have added image into screensort in "SinglePlayer - Games/Banner - image" in this section*
- [x] I have added game into "additionalpage/game.html"*
- [x] I have added Update main README.md file*

## Task

- [ ] Follow Us On social media -
- [x]      <a href="https://github.com/GameSphere-MultiPlayer" target="_blank">GitHub</a>
- [x]      <a href="https://www.linkedin.com/company/gamesphere-multiplayer/" target="_blank">LinkedIn</a>
- [x]     <a href="https://www.youtube.com/@durgesh4993/channels" target="_blank">YouTube</a>
- [x]      <a href="https://discord.com/invite/dakzwdz4ev" target="_blank">Discord</a>

## Enter you User Id's:
LinkedIn:
<br>GitHub: 
<br>YouTube:
<br>Discord:

If you Follow us in both social medias we provide 'level2' 
*Only First time

### CODE REVIEW

**Comment by Amancoder-01** [comment]
@Damini2004 Resolve Conflicting files

**Comment by Damini2004** [comment]
@Amancoder-01 Resolved kinldy check it

**Comment by Damini2004** [comment]
@Amancoder-01 Kinldy go through this pr

**Comment by Damini2004** [comment]
@Amancoder-01 Review again

**Pull request merged**
