### PR TITLE
Basketball is added

### PR DESCRIPTION
**Pull request by pallasivasai**
## Related Issue*

#957 

## Description

Basketball is added

## Screenshot Section

Baseball_Game

## Demo Video Section*

https://github.com/GameSphere-MultiPlayer/GameSphere/assets/56314427/824c12a2-ceeb-433a-adee-50d155a45a7c

## Checklist 

- [x] I have added image into screensort in "SinglePlayer - Games/Banner - image" in this section*
- [x] I have added game into "additionalpage/game.html"*
- [x] I have added Update main README.md file*

## Task

- [x] Follow Us On social media -
- [x]      <a href="https://github.com/GameSphere-MultiPlayer" target="_blank">GitHub</a>
- [x]      <a href="https://www.linkedin.com/company/gamesphere-multiplayer/" target="_blank">LinkedIn</a>
- [x]     <a href="https://www.youtube.com/@durgesh4993/channels" target="_blank">YouTube</a>
- [x]      <a href="https://discord.com/invite/dakzwdz4ev" target="_blank">Discord</a>

## Enter you User Id's:
LinkedIn: https://www.linkedin.com/in/p-siva-sai-10686417a/
<br>GitHub: Pallasivasai
<br>YouTube:
<br>Discord: psivasai (recently joined)

If you Follow us in both social medias we provide 'level2' 
*Only First time

### CODE REVIEW

**Review by Durgesh4993 — APPROVED** [review]
Ok

**Comment by Durgesh4993** [comment]
@pallasivasai Resolve conflict

**Comment by Amancoder-01** [comment]
Please resolve Conflicting files

**Comment by Durgesh4993** [comment]
@pallasivasai resolve conflicting files

**Pull request merged**
