### PR TITLE
Feat : Add Tug of war game

### PR DESCRIPTION
**Pull request by Meetjain1**
### PR Description

**Added Tug of War Game**

This PR introduces a fully functional and interactive two-player Tug of War game. Below are the key features and updates included:

- **Game Mechanics**:
  - Player 1 uses the "A" key, and Player 2 uses the "L" key to play.
  - The marker moves towards the player who presses their key more rapidly.
  - The first player to reach the winning score of 10 wins the game.
  
- **User Interface**:
  - Clean and responsive design using HTML, CSS, and JavaScript.
  - Scoreboard displaying the current scores of both players.
  - Visual representation of the game with a rope and a marker indicating the players' progress.

- **Game Controls**:
  - **Start Game**: Initiates a 5-second countdown before the game begins.
  - **Reset Game**: Refreshes the page, resetting the game to its initial state with the marker at the center and scores set to 0.

- **Additional Features**:
  - Countdown timer displayed before the game starts.
  - Congratulatory message displayed for the winning player.
  
This game enhances user interaction and provides an engaging way to compete. The responsive design ensures compatibility across various devices.

## Screenshot Section
t1
t2

## Checklist 

- [X] I have added image into screensort in "SinglePlayer - Games/Banner - image" in this section*
- [X] I have added game into "additionalpage/game.html"*
- [X] I have added Update main README.md file*

## Task

- [X] Follow Us On social media -
- [X]      <a href="https://github.com/GameSphere-MultiPlayer" target="_blank">GitHub</a>
- [X]      <a href="https://www.linkedin.com/company/gamesphere-multiplayer/" target="_blank">LinkedIn</a>
- [X]     <a href="https://www.youtube.com/@durgesh4993/channels" target="_blank">YouTube</a>
- [X]      <a href="https://discord.com/invite/dakzwdz4ev" target="_blank">Discord</a>

## Enter you User Id's:
LinkedIn:
<br>GitHub: 
<br>YouTube:
<br>Discord:

If you Follow us in both social medias we provide 'level2' 
*Only First time

### CODE REVIEW

**Review by Durgesh4993 — COMMENTED** [review]
Resolve Conflicting files

**Comment by Meetjain1** [comment]
> @Durgesh4993 Resolved
> 
> > Resolve Conflicting files
> 
> @Durgesh4993 Resolved

@Durgesh4993 have a look

**Comment by Meetjain1** [comment]
@Durgesh4993 please review this pr . Conflicts solved

**Comment by Meetjain1** [comment]
> @Durgesh4993 please review this pr . Conflicts solved

@Durgesh4993

**Comment by Meetjain1** [comment]
@Durgesh4993 please review this pr . Thanks

**Comment by Meetjain1** [comment]
@Durgesh4993 conflicts resolved please check

**Comment by Meetjain1** [comment]
@Durgesh4993  please review this pr . Thanks

**Comment by Meetjain1** [comment]
@Durgesh4993 conflicts resolved again , please review this pf first so that conflicts will not arise again . Thanks

**Pull request merged**
