### PR TITLE
Box Merge Game

### LINKED ISSUE #1087: [New game]: Box Merge Game
### Box Merge Game

This game implements the mechanics you described:

The player controls a colored box using arrow keys.
There are several other colored boxes randomly placed in the game area.
When the player's box touches another box of the same color, they merge, and the player's box grows larger.
If the player's box touches a box of a different color, it shrinks.
The game keeps track of the score, increasing it when merging and decreasing it when shrinking.

### Game Preview

https://github.com/user-attachments/assets/fe7268b5-0101-40bd-9162-2ef8d05b3474

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/GameSphere-MultiPlayer/GameSphere/blob/main/.github/Contributor.md) of this project.

### PR DESCRIPTION
**Pull request by Anjaliavv51**
#1087

## Related Issue*

Closes #1087 

### Box Merge Game

This game implements the mechanics you described:

The player controls a colored box using arrow keys.
There are several other colored boxes randomly placed in the game area.
When the player's box touches another box of the same color, they merge, and the player's box grows larger.
If the player's box touches a box of a different color, it shrinks.
The game keeps track of the score, increasing it when merging and decreasing it when shrinking.

### Game Preview

https://github.com/user-attachments/assets/fe7268b5-0101-40bd-9162-2ef8d05b3474

## Checklist 

- [X] I have added image into screensort in "SinglePlayer - Games/Banner - image" in this section*
- [X] I have added game into "additionalpage/game.html"*
- [X] I have added Update main README.md file*

## Task

Follow Us On social media -
- [X]      <a href="https://github.com/GameSphere-MultiPlayer" target="_blank">GitHub</a>
- [X]      <a href="https://www.linkedin.com/company/gamesphere-multiplayer/" target="_blank">LinkedIn</a>
- [X]     <a href="https://www.youtube.com/@durgesh4993/channels" target="_blank">YouTube</a>
- [X]      <a href="https://discord.com/invite/dakzwdz4ev" target="_blank">Discord</a>

### CODE REVIEW

**Comment by Anjaliavv51** [comment]
@Durgesh4993 please review the PR.

**Comment by Anjaliavv51** [comment]
@Durgesh4993 @Amancoder-01 please assign me this issue

**Comment by Anjaliavv51** [comment]
@Durgesh4993 @Amancoder-01 please assign me this issue

**Review by Durgesh4993 — APPROVED** [review]
Approved

**Pull request merged**
