### PR TITLE
Ball_Shooting_Game

### LINKED ISSUE #919: [Game]: want to add Ball Shooting game
## Game Name
Ball Shooting game

## Description

this is very simple and very good decent shooting game

### Connect Us On Social Media -
- [x]  Star the repositry
- [x]  <a href="https://github.com/GameSphere-MultiPlayer" target="_blank">GitHub</a>
- [x]   <a href="https://www.linkedin.com/company/gamesphere-multiplayer/" target="_blank">LinkedIn</a>
- [x]   <a href="https://www.youtube.com/@durgesh4993/channels" target="_blank">YouTube</a>
- [x]    <a href="https://discord.com/invite/dakzwdz4ev" target="_blank">Discord</a>

### PR DESCRIPTION
**Pull request by pallasivasai**
## Related Issue*

Closes #919 

## Description

this is an Ball_Shooting_Game so interesting game please check this video at onces! 

## Screenshot Section

Ball_Shooting_Game

## Demo Video Section*

https://drive.google.com/file/d/1vLrVFp5nSqU21hGdf7Rwf5dSYXTfDCwr/view?usp=sharing

## Checklist 

- [x] I have added image into screensort in "SinglePlayer - Games/Banner - image" in this section*
- [x] I have added game into "additionalpage/game.html"*
- [x] I have added Update main README.md file*

## Task

- [x] Follow Us On social media -
- [x]      <a href="https://github.com/GameSphere-MultiPlayer" target="_blank">GitHub</a>
- [x]      <a href="https://www.linkedin.com/company/gamesphere-multiplayer/" target="_blank">LinkedIn</a>
- [x]     <a href="https://www.youtube.com/@durgesh4993/channels" target="_blank">YouTube</a>
- [x]      <a href="https://discord.com/invite/dakzwdz4ev" target="_blank">Discord</a>

## Enter you User Id's:
LinkedIn:
<br>GitHub: pallasivasai
<br>YouTube: p siva sai(Palla siva sai))
<br>Discord:

If you Follow us in both social medias we provide 'level2' 
*Only First time

### CODE REVIEW

**Review by Durgesh4993 — APPROVED** [review]
Ok

**Comment by Durgesh4993** [comment]
If you have any doubt you can directly send message on our discord (https://discord.gg/rZb46cCMmK), we have created seprate chennals for all projects...

Connect Us :
LinkedIn: https://www.linkedin.com/company/chromegaming
GitHub: https://github.com/GameSphere-MultiPlayer

Thank you :)

**Comment by pallasivasai** [comment]
please merge those PRS so that I can do New PRS from now @Durgesh4993

**Comment by Amancoder-01** [comment]
@pallasivasai resolve the conflict

**Comment by pallasivasai** [comment]
Done please check! @Durgesh4993 @Amancoder-01

**Comment by pallasivasai** [comment]
please merge this PR so that I can do rest of PRS

**Pull request merged**
