### PR TITLE
Removed additional scroll bar on console image hover

### LINKED ISSUE #1027: [Bug]: Remove x axis scrollbar
### Give a brief about the bug ✍️

Description -> A scroll bar appears on the x axis when we hover on the hero section game pad image

Image ->

image

### What is the expected behavior? 🤔

Description -> There should not be any scroll bar on the x axis

### Provide step by step information reproduce the bug 📄

Description ->
1. Go to the `Home` page
2. Hover over the hero section image
3. Notice the scroll bar on the x axis (on the bottom half of the screen)

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/GameSphere-MultiPlayer/GameSphere/blob/main/.github/Contributor.md) of this project.

### PR DESCRIPTION
**Pull request by SaranshBangar**
## Related Issue*

Closes #1027 

## Description

I have added additional css properties in the `style.css` file to prevent x - axis scroll bar on hover over `Console` image

## Screenshot Section

image

## Checklist 

- [ ] I have added image into screensort in "SinglePlayer - Games/Banner - image" in this section*
- [ ] I have added game into "additionalpage/game.html"*
- [ ] I have added Update main README.md file*

## Task

- [ ] Follow Us On social media -
- [X]      <a href="https://github.com/GameSphere-MultiPlayer" target="_blank">GitHub</a>
- [X]      <a href="https://www.linkedin.com/company/gamesphere-multiplayer/" target="_blank">LinkedIn</a>
- [X]     <a href="https://www.youtube.com/@durgesh4993/channels" target="_blank">YouTube</a>
- [X]      <a href="https://discord.com/invite/dakzwdz4ev" target="_blank">Discord</a>

## Enter you User Id's:
LinkedIn: https://www.linkedin.com/in/saransh-bangar/
<br>GitHub: @SaranshBangar
<br>Discord: SaranshBangar#6658

If you Follow us in both social medias we provide 'level2' (Followed on GitHub and YouTube)
*Only First time

### CODE REVIEW

**Comment by SaranshBangar** [comment]
Resolves issue #1027

**Review by Durgesh4993 — APPROVED** [review]
Ok

**Review by Durgesh4993 — CHANGES_REQUESTED** [review]
Remove logo and add new logo of chrome gaming

**Comment by SaranshBangar** [comment]
Ok sir

**Pull request merged**
